# =============================================================================
#  portmap.nim - Verilog Port Extractor
#  Language: Nim 1.6+
#
#  BUILD:
#    nim c -d:release portmap.nim
#
#  RUN (default: pretty table):
#    nim c portmap.nim <file.v>
#    ./portmap <file.v>
#
#  RUN (Markdown output):
#    nim c -r portmap.nim <file.v> --md
#    ./portmap <file.v> --md
#
#  INSTALL NIM 
# (Linux/macOS): sudo apt install nim
# verify by: nim --verrsion
# =============================================================================

import std/os
import std/strutils
import std/sequtils

type
  Port = object
    name:      string
    direction: string
    width:     string

proc extractWidth(tokens: seq[string]): string =
  for tok in tokens:
    if tok.startsWith("["):
      return tok
  return "1"

proc extractName(tokens: seq[string]): string =
  if tokens.len == 0: return ""
  var name = tokens[^1]
  name = name.replace(",", "")
  name = name.replace(";", "")
  name = name.replace(")", "")
  return name.strip()

proc parsePorts(filePath: string): seq[Port] =
  var ports: seq[Port] = @[]

  let content = readFile(filePath)
  let lines = content.split("\n")

  for rawLine in lines:
    var line = rawLine.strip()

    if line.len == 0: continue

    let commentIdx = line.find("//")
    if commentIdx >= 0:
      line = line[0 ..< commentIdx].strip()

    if line.startsWith("/*") or
       line.startsWith("*")  or
       line.startsWith("module") or
       line.startsWith("endmodule") or
       line.startsWith("#(") or
       line.startsWith("parameter"):
      continue

    let lower = line.toLowerAscii()

    var direction = ""
    if lower.startsWith("input"):    direction = "input"
    elif lower.startsWith("output"): direction = "output"
    elif lower.startsWith("inout"):  direction = "inout"
    else: continue

    let tokens = line.split(" ").filterIt(it.len > 0)

    if tokens.len < 2: continue

    let payload = tokens[1 .. ^1]

    let meaningful = payload.filterIt(
      it != "wire" and it != "reg" and it != "logic" and
      it != "signed" and it != "unsigned"
    )

    if meaningful.len == 0: continue

    var p: Port
    p.direction = direction
    p.width     = extractWidth(meaningful)
    p.name      = extractName(meaningful)

    if p.name.len == 0 or p.name.startsWith("["): continue

    ports.add(p)

  return ports

proc renderTable(ports: seq[Port], filePath: string) =
  let fname = filePath.extractFilename()

  echo ""
  echo "Port Map — " & fname
  echo ""

  echo "+----------+-----------+--------+"
  echo "| Port     | Direction | Width  |"
  echo "+----------+-----------+--------+"

  for p in ports:
    let name = alignLeft(p.name, 8)
    let dir  = alignLeft(p.direction, 9)
    let wid  = alignLeft(p.width, 6)

    echo "| " & name & " | " & dir & " | " & wid & " |"

  echo "+----------+-----------+--------+"
  echo ""

proc renderMarkdown(ports: seq[Port], filePath: string) =
  let fname = filePath.extractFilename()

  echo ""
  echo "### Port Map — `" & fname & "`"
  echo ""
  echo "| Port | Direction | Width |"
  echo "|------|-----------|-------|"

  for p in ports:
    echo "| `" & p.name & "` | " & p.direction & " | " & p.width & " |"

  echo ""
  echo "> *Generated by [portmap](https://github.com/KARAN-D05) — Nim port extractor*"
  echo ""

when isMainModule:

  if paramCount() < 1:
    echo "portmap — Verilog port extractor"
    echo "Usage:  portmap <file.v> [file2.v ...] [--md]"
    echo "Output: Pretty table (default) or Markdown with --md"
    quit(1)

  var useMarkdown = false

  for i in 1 .. paramCount():
    if paramStr(i) == "--md":
      useMarkdown = true

  for i in 1 .. paramCount():
    let path = paramStr(i)

    if path == "--md": continue

    if not fileExists(path):
      stderr.writeLine("ERROR: file not found: " & path)
      continue

    let ports = parsePorts(path)

    if ports.len == 0:
      stderr.writeLine("WARNING: no ports found in " & path)
    else:
      if useMarkdown:
        renderMarkdown(ports, path)
      else:
        renderTable(ports, path)
