set HDL_EXTENSIONS {.v .sv .vh .svh}

set TB_SUFFIXES {_tb _test _sim tb_ testbench}

proc string_contains {str sub} {
    
    set idx [string first [string tolower $sub] [string tolower $str]]
    return [expr {$idx >= 0}]   ;
}

proc is_testbench {fname} {
    global TB_SUFFIXES   ;
    
    set stem [file rootname $fname]   ;

    foreach suffix $TB_SUFFIXES {
        if {[string_contains $stem $suffix]} {
            return 1
        }
    }
    return 0
}

proc get_extension {fname} {
    
    return [string tolower [file extension $fname]]
}

proc count_lines {fpath} {
    
    set fh [open $fpath r]
    set count 0

    while {[gets $fh line] >= 0} {
        set trimmed [string trim $line]   ;

        if {$trimmed eq ""} continue

        if {[string match "//*" $trimmed]} continue

        if {[string index $trimmed 0] eq "*"} continue
        if {[string match "/*" $trimmed]} continue

        incr count   ;
    }

    close $fh
    return $count
}

proc count_modules {fpath} {
    set fh [open $fpath r]
    set count 0

    while {[gets $fh line] >= 0} {
        set trimmed [string trim $line]

        if {[string match "//*" $trimmed]} continue

        if {[regexp {^\s*module\s+} $trimmed]} {
            incr count
        }
    }

    close $fh
    return $count
}

proc walk_directory {root} {
    global HDL_EXTENSIONS

    set result {}   ;
    
    foreach ext $HDL_EXTENSIONS {
        set pattern [file join $root "*${ext}"]
        foreach f [glob -nocomplain $pattern] {
            lappend result $f   ;
        }
    }

    foreach subdir [glob -nocomplain -type d [file join $root "*"]] {
      
        set dname [file tail $subdir]   ;
        if {[string match ".*" $dname]} continue

        
        set sub_files [walk_directory $subdir]
        set result [concat $result $sub_files]   ;
    }

    return $result
}

proc render_card {stats} {

    set repo_name  [dict get $stats name]
    set hdl_files  [dict get $stats hdl_files]
    set modules    [dict get $stats modules]
    set hdl_lines  [dict get $stats hdl_lines]
    set testbenches [dict get $stats testbenches]
    set sv_files   [dict get $stats sv_files]

   
    puts ""
    puts "```"
    puts "╔══════════════════════════════════════╗"
    set title " $repo_name "
    set pad_total [expr {38 - [string length $title]}]
    set pad_left  [expr {$pad_total / 2}]
    set pad_right [expr {$pad_total - $pad_left}]
    puts "║[string repeat " " $pad_left]${title}[string repeat " " $pad_right]║"
    puts "╠══════════════════════════════════════╣"

    puts [format "║  %-20s %15s  ║" "HDL Files"   $hdl_files]
    puts [format "║  %-20s %15s  ║" "  of which .sv"  $sv_files]
    puts [format "║  %-20s %15s  ║" "Modules"     $modules]
    puts [format "║  %-20s %15s  ║" "HDL Lines"   $hdl_lines]
    puts [format "║  %-20s %15s  ║" "Testbenches" $testbenches]
    puts "╚══════════════════════════════════════╝"
    puts "```"
    puts ""
    puts {> *Generated by [repocard](https://github.com/KARAN-D05) — Tcl repo stats*}
    puts ""
}

if {[llength $argv] > 0} {
    set root [lindex $argv 0]   ;
} else {
    set root [pwd]              ;
}

if {![file isdirectory $root]} {
    puts stderr "ERROR: not a directory: $root"
    exit 1
}

set repo_name [file tail $root]

if {$repo_name eq "."} {
    set repo_name [file tail [file normalize $root]]
}

set all_files [walk_directory $root]

set total_hdl   0   ;
set total_sv    0   ;
set total_mod   0   ;
set total_lines 0   ;
set total_tb    0   ;

foreach fpath $all_files {
    set fname [file tail $fpath]
    set ext   [get_extension $fname]

    incr total_hdl

    if {$ext eq ".sv" || $ext eq ".svh"} { incr total_sv }
    if {[is_testbench $fname]}           { incr total_tb  }

    incr total_mod   [count_modules $fpath]
    incr total_lines [count_lines   $fpath]
}

set stats [dict create \
    name        $repo_name  \
    hdl_files   $total_hdl  \
    sv_files    $total_sv   \
    modules     $total_mod  \
    hdl_lines   $total_lines \
    testbenches $total_tb   \
]

render_card $stats
